Vagrant.configure("2") do |config|

  config.vm.box = "debian/jessie64"
  config.vm.box_version = "8.10.0"

  config.vm.network :private_network, ip: "192.168.100.101"

  config.vm.provision :shell, path: "./post-install.sh"

  config.vm.provider :virtualbox do |vb|

    vb.name = "KataCodasDocker"
    vb.memory = 2048
  end
end
